### ISSUE TITLE
I can't find the clyphx as a control surface

### ISSUE THREAD

**Issue by lucasloyato** [ldrolez/clyphx-live10#22] opened 2022-02-27 01:53 UTC
Hi, i'm using Ableton Live 11 Trial version.

I've followed every step indicated on the installation but it's not working anyway.

![live](https://user-images.githubusercontent.com/37811632/155865052-7e8d48cf-242e-4b78-9a92-0c57cf4ae7c8.jpg) This is how my user library looks like from the browser.

Please let me know what else i can do.

Thank you very much for doing this.

**Comment by ldrolez** [comment] 2022-02-27 08:25
Yes you unpacked it in the wrong folder. The best:

- From the Live Browser, head to your "User Library". and create a folder "Remote Scripts"
- Right click this folder and select "show in finder/explorer".
- Copy there the ClyphX folder from the ZIP.

**Comment by ldrolez** [comment] 2022-02-27 08:27
duplicate of #21

**Comment by ldrolez** [comment] 2022-02-27 08:33
Will update the readme your install should look like this:
![image](https://user-images.githubusercontent.com/2277898/155874914-d16fd93a-536a-4cb3-bba2-3935345bf2a7.png)

**Closed** 2022-02-27 08:33 UTC

**Comment by lucasloyato** [comment] 2022-02-27 18:09
Hi, it remains the same. 

![1](https://user-images.githubusercontent.com/37811632/155894270-c0d9b4b7-fe7b-4a22-93b2-56e1786eef5f.jpg)

![2](https://user-images.githubusercontent.com/37811632/155894274-e30231e2-4ff8-4b4c-a304-181979f0ebfb.jpg)

![3](https://user-images.githubusercontent.com/37811632/155894277-de7f6138-b583-4756-ae72-079c17c1276d.jpg)

![4](https://user-images.githubusercontent.com/37811632/155894281-79cc6f0c-85fb-4d6c-8a8b-b731d727faaa.jpg)

**Comment by ldrolez** [comment] 2022-02-28 15:08
In the ClyphX directory do you see the file Clyphx.py?

**Comment by lucasloyato** [comment] 2022-03-01 22:25
Yes, here it is.

![imagen](https://user-images.githubusercontent.com/37811632/156259158-b4be6b85-9073-4f3a-a432-63cc5c1313e1.png)

**Comment by ldrolez** [comment] 2022-03-04 20:41
Still nothing in the link/tempo/midi menu?

**Comment by lucasloyato** [comment] 2022-03-07 14:14
No, still nothing.
